version: "3"
services:
  chatbot:
    image: pzaerial/chatbot
    container_name: chatbot_pzaerial_whitney
    restart: always
    build: .
    ports:
      - "7081:7081"
    volumes:
      - "./data.json:/etc/chatBot/data.json"
      - "./config.json:/etc/chatBot/config.json"
